---

- hosts: localhost
  tasks:

    - name: install OS packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      loop:
        - jq
        - tmux
        - neovim
        - git
        - zsh
        - vlc

    - name: install tfenv
      shell: git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv

    - name: install kubectl
      block:
        - name: install kubectl for x86_64
          shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          when: ansible_architecture == "x86_64"
        - name: install kubectl for arm64
          shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
          when: ansible_architecture == "aarch64"
        - name: install kubectl
          become: yes
          shell: install kubectl /usr/local/bin/kubectl

    - name: get vimrc
      get_url:
        url: "https://raw.githubusercontent.com/maxdotdotg/mynewworkstation/master/.vimrc"
        dest: "~/.vimrc"

    - name: ensure .config/nvim dir exists
      file:
        path: "~/.config/nvim"
        state: directory

    - name: symlink vimrc for nvim
      file:
        src: "~/.vimrc"
        dest: "~/.config/nvim/init.vim"
        state: link

    - name: get tmux conf
      get_url:
        url: "https://raw.githubusercontent.com/maxdotdotg/mynewworkstation/master/.tmux.conf"
        dest: "~/.tmux.conf"

    - name: install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

    - name: render zshrc
      template:
        src: templates/zshrc.j2
        dest: "~/.zshrc"
